/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ADBScreenshotIn } from './models/ADBScreenshotIn';
export type { ADBScreenshotOut } from './models/ADBScreenshotOut';
export type { BackendHealthOut } from './models/BackendHealthOut';
export type { BetterGIConfig } from './models/BetterGIConfig';
export type { BetterGIConfig_Game } from './models/BetterGIConfig_Game';
export type { BetterGICustomGroupOut } from './models/BetterGICustomGroupOut';
export type { BetterGICustomGroupsOut } from './models/BetterGICustomGroupsOut';
export type { BetterGIUserConfig } from './models/BetterGIUserConfig';
export type { BetterGIUserConfig_Data } from './models/BetterGIUserConfig_Data';
export type { BetterGIUserConfig_Info } from './models/BetterGIUserConfig_Info';
export type { BetterGIUserConfig_OneDragon } from './models/BetterGIUserConfig_OneDragon';
export type { BetterGIUserConfig_Switch } from './models/BetterGIUserConfig_Switch';
export type { BetterGIUserConfig_Task } from './models/BetterGIUserConfig_Task';
export type { Body_batch_update_oknte_configs_api_scripts_oknte_configs_batch_update_post } from './models/Body_batch_update_oknte_configs_api_scripts_oknte_configs_batch_update_post';
export type { Body_update_oknte_config_api_scripts_oknte_configs_update_post } from './models/Body_update_oknte_config_api_scripts_oknte_configs_update_post';
export type { CheckImageAllIn } from './models/CheckImageAllIn';
export type { CheckImageAnyIn } from './models/CheckImageAnyIn';
export type { CheckImageIn } from './models/CheckImageIn';
export type { CheckImageOut } from './models/CheckImageOut';
export type { ClickImageIn } from './models/ClickImageIn';
export type { ClickOut } from './models/ClickOut';
export type { ClickTextIn } from './models/ClickTextIn';
export type { ComboBoxItem } from './models/ComboBoxItem';
export type { ComboBoxOut } from './models/ComboBoxOut';
export type { DeviceInfo } from './models/DeviceInfo';
export type { DispatchIn } from './models/DispatchIn';
export type { EmulatorConfig } from './models/EmulatorConfig';
export type { EmulatorConfig_Info } from './models/EmulatorConfig_Info';
export type { EmulatorConfigIndexItem } from './models/EmulatorConfigIndexItem';
export type { EmulatorCreateOut } from './models/EmulatorCreateOut';
export type { EmulatorDeleteIn } from './models/EmulatorDeleteIn';
export type { EmulatorGetIn } from './models/EmulatorGetIn';
export type { EmulatorGetOut } from './models/EmulatorGetOut';
export { EmulatorOperateIn } from './models/EmulatorOperateIn';
export type { EmulatorReorderIn } from './models/EmulatorReorderIn';
export type { EmulatorSearchOut } from './models/EmulatorSearchOut';
export type { EmulatorSearchResult } from './models/EmulatorSearchResult';
export type { EmulatorStatusOut } from './models/EmulatorStatusOut';
export type { EmulatorUpdateIn } from './models/EmulatorUpdateIn';
export type { GameSignAccountCreateOut } from './models/GameSignAccountCreateOut';
export type { GameSignAccountDeleteIn } from './models/GameSignAccountDeleteIn';
export type { GameSignAccountGetIn } from './models/GameSignAccountGetIn';
export type { GameSignAccountGroupConfig } from './models/GameSignAccountGroupConfig';
export type { GameSignAccountReorderIn } from './models/GameSignAccountReorderIn';
export type { GameSignAccountsListOut } from './models/GameSignAccountsListOut';
export type { GameSignAccountUpdateIn } from './models/GameSignAccountUpdateIn';
export type { GeneralConfig } from './models/GeneralConfig';
export type { GeneralConfig_Game } from './models/GeneralConfig_Game';
export type { GeneralConfig_Info } from './models/GeneralConfig_Info';
export type { GeneralConfig_Run } from './models/GeneralConfig_Run';
export type { GeneralConfig_Script } from './models/GeneralConfig_Script';
export type { GeneralUserConfig } from './models/GeneralUserConfig';
export type { GeneralUserConfig_Data } from './models/GeneralUserConfig_Data';
export type { GeneralUserConfig_Info } from './models/GeneralUserConfig_Info';
export type { GeneralUserConfig_Notify } from './models/GeneralUserConfig_Notify';
export { GetStageIn } from './models/GetStageIn';
export type { GlobalConfig } from './models/GlobalConfig';
export type { GlobalConfig_Function } from './models/GlobalConfig_Function';
export type { GlobalConfig_Notify } from './models/GlobalConfig_Notify';
export type { GlobalConfig_Start } from './models/GlobalConfig_Start';
export type { GlobalConfig_UI } from './models/GlobalConfig_UI';
export type { GlobalConfig_Update } from './models/GlobalConfig_Update';
export type { GlobalConfig_Voice } from './models/GlobalConfig_Voice';
export type { HistoryData } from './models/HistoryData';
export type { HistoryDataGetIn } from './models/HistoryDataGetIn';
export type { HistoryDataGetOut } from './models/HistoryDataGetOut';
export { HistoryIndexItem } from './models/HistoryIndexItem';
export { HistorySearchIn } from './models/HistorySearchIn';
export type { HistorySearchOut } from './models/HistorySearchOut';
export type { HSRCapabilitiesData } from './models/HSRCapabilitiesData';
export type { HSRCapabilitiesOut } from './models/HSRCapabilitiesOut';
export { HSRCapabilityAdapter } from './models/HSRCapabilityAdapter';
export { HSRCapabilityTask } from './models/HSRCapabilityTask';
export type { HSRConfig } from './models/HSRConfig';
export type { HSRConfig_Game } from './models/HSRConfig_Game';
export type { HSRConfig_Info } from './models/HSRConfig_Info';
export type { HSRConfig_Run } from './models/HSRConfig_Run';
export type { HSRConfig_TaskMapping } from './models/HSRConfig_TaskMapping';
export { HSRDirectConfigImportData } from './models/HSRDirectConfigImportData';
export { HSRDirectConfigImportIn } from './models/HSRDirectConfigImportIn';
export type { HSRDirectConfigImportOut } from './models/HSRDirectConfigImportOut';
export type { HSRDynamicStageCategory } from './models/HSRDynamicStageCategory';
export type { HSRDynamicStageM7A } from './models/HSRDynamicStageM7A';
export type { HSRDynamicStageOption } from './models/HSRDynamicStageOption';
export type { HSRDynamicStageSRA } from './models/HSRDynamicStageSRA';
export type { HSRManagedConfigData } from './models/HSRManagedConfigData';
export type { HSRManagedConfigOut } from './models/HSRManagedConfigOut';
export { HSRManagedDroppedOverride } from './models/HSRManagedDroppedOverride';
export type { HSRManagedField } from './models/HSRManagedField';
export { HSRManagedForm } from './models/HSRManagedForm';
export { HSRManagedTask } from './models/HSRManagedTask';
export type { HSRSRAProfile } from './models/HSRSRAProfile';
export type { HSRSRAProfilesData } from './models/HSRSRAProfilesData';
export type { HSRSRAProfilesOut } from './models/HSRSRAProfilesOut';
export { HSRStageOptionsData } from './models/HSRStageOptionsData';
export type { HSRStageOptionsOut } from './models/HSRStageOptionsOut';
export type { HSRUserConfig } from './models/HSRUserConfig';
export type { HSRUserConfig_Control } from './models/HSRUserConfig_Control';
export type { HSRUserConfig_Data } from './models/HSRUserConfig_Data';
export type { HSRUserConfig_Direct } from './models/HSRUserConfig_Direct';
export type { HSRUserConfig_Info } from './models/HSRUserConfig_Info';
export type { HSRUserConfig_Managed } from './models/HSRUserConfig_Managed';
export type { HSRUserConfig_Notify } from './models/HSRUserConfig_Notify';
export type { HSRUserConfig_Stage } from './models/HSRUserConfig_Stage';
export type { HSRUserConfig_TaskOpt } from './models/HSRUserConfig_TaskOpt';
export type { HSRUserConfig_TaskSwitch } from './models/HSRUserConfig_TaskSwitch';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { InfoOut } from './models/InfoOut';
export type { M9AConfig } from './models/M9AConfig';
export type { M9AConfig_Emulator } from './models/M9AConfig_Emulator';
export type { M9AConfig_Info } from './models/M9AConfig_Info';
export type { M9AConfig_Run } from './models/M9AConfig_Run';
export type { M9AUserConfig } from './models/M9AUserConfig';
export type { M9AUserConfig_Data } from './models/M9AUserConfig_Data';
export type { M9AUserConfig_Info } from './models/M9AUserConfig_Info';
export type { M9AUserConfig_Notify } from './models/M9AUserConfig_Notify';
export type { M9AUserConfig_Task } from './models/M9AUserConfig_Task';
export type { MaaConfig } from './models/MaaConfig';
export type { MaaConfig_Emulator } from './models/MaaConfig_Emulator';
export type { MaaConfig_Info } from './models/MaaConfig_Info';
export type { MaaConfig_Run } from './models/MaaConfig_Run';
export type { MaaEndAutoEssencePlanKey } from './models/MaaEndAutoEssencePlanKey';
export type { MaaEndConfig } from './models/MaaEndConfig';
export type { MaaEndConfig_Game } from './models/MaaEndConfig_Game';
export type { MaaEndConfig_Info } from './models/MaaEndConfig_Info';
export type { MaaEndConfig_Run } from './models/MaaEndConfig_Run';
export type { MaaEndOptionsOut } from './models/MaaEndOptionsOut';
export { MaaEndPlanConfig_Info } from './models/MaaEndPlanConfig_Info';
export type { MaaEndPlanConfig_Input } from './models/MaaEndPlanConfig_Input';
export type { MaaEndPlanConfig_Item } from './models/MaaEndPlanConfig_Item';
export type { MaaEndPlanConfig_Output } from './models/MaaEndPlanConfig_Output';
export { MaaEndProtocolSpacePlanKey } from './models/MaaEndProtocolSpacePlanKey';
export type { MaaEndUserConfig } from './models/MaaEndUserConfig';
export type { MaaEndUserConfig_Data } from './models/MaaEndUserConfig_Data';
export type { MaaEndUserConfig_Info } from './models/MaaEndUserConfig_Info';
export type { MaaEndUserConfig_Notify } from './models/MaaEndUserConfig_Notify';
export type { MaaEndUserConfig_Task } from './models/MaaEndUserConfig_Task';
export type { MaaFWAdbEmulatorExtraCapabilityInfo } from './models/MaaFWAdbEmulatorExtraCapabilityInfo';
export type { MaaFWAgentEnvInfo } from './models/MaaFWAgentEnvInfo';
export type { MaaFWAgentEnvPrepareData } from './models/MaaFWAgentEnvPrepareData';
export type { MaaFWAgentEnvPrepareIn } from './models/MaaFWAgentEnvPrepareIn';
export type { MaaFWAgentEnvPrepareOut } from './models/MaaFWAgentEnvPrepareOut';
export type { MaaFWConfig } from './models/MaaFWConfig';
export type { MaaFWConfig_Device } from './models/MaaFWConfig_Device';
export type { MaaFWConfig_Emulator } from './models/MaaFWConfig_Emulator';
export type { MaaFWConfig_Game } from './models/MaaFWConfig_Game';
export type { MaaFWConfig_Info } from './models/MaaFWConfig_Info';
export type { MaaFWConfig_Managed } from './models/MaaFWConfig_Managed';
export type { MaaFWConfig_ManagedRemote } from './models/MaaFWConfig_ManagedRemote';
export type { MaaFWConfig_ManagedRuntime } from './models/MaaFWConfig_ManagedRuntime';
export type { MaaFWConfig_Run } from './models/MaaFWConfig_Run';
export type { MaaFWConfig_Selection } from './models/MaaFWConfig_Selection';
export type { MaaFWConfig_Update } from './models/MaaFWConfig_Update';
export type { MaaFWControlCapabilitiesInfo } from './models/MaaFWControlCapabilitiesInfo';
export type { MaaFWControllerInfo } from './models/MaaFWControllerInfo';
export type { MaaFWGroupInfo } from './models/MaaFWGroupInfo';
export type { MaaFWInterfacePreviewData } from './models/MaaFWInterfacePreviewData';
export type { MaaFWInterfacePreviewIn } from './models/MaaFWInterfacePreviewIn';
export type { MaaFWInterfacePreviewOut } from './models/MaaFWInterfacePreviewOut';
export type { MaaFWOptionCaseInfo } from './models/MaaFWOptionCaseInfo';
export type { MaaFWOptionHotkeyInfo } from './models/MaaFWOptionHotkeyInfo';
export type { MaaFWOptionInfo } from './models/MaaFWOptionInfo';
export type { MaaFWOptionInputInfo } from './models/MaaFWOptionInputInfo';
export type { MaaFWPresetInfo } from './models/MaaFWPresetInfo';
export type { MaaFWProjectInfo } from './models/MaaFWProjectInfo';
export type { MaaFWProjectUpdateData } from './models/MaaFWProjectUpdateData';
export { MaaFWProjectUpdateIn } from './models/MaaFWProjectUpdateIn';
export type { MaaFWProjectUpdateOut } from './models/MaaFWProjectUpdateOut';
export type { MaaFWResourceInfo } from './models/MaaFWResourceInfo';
export type { MaaFWSettingInfo } from './models/MaaFWSettingInfo';
export type { MaaFWTaskInfo } from './models/MaaFWTaskInfo';
export type { MaaFWTaskSnapshot } from './models/MaaFWTaskSnapshot';
export type { MaaFWUserConfig } from './models/MaaFWUserConfig';
export type { MaaFWUserConfig_Data } from './models/MaaFWUserConfig_Data';
export type { MaaFWUserConfig_Device } from './models/MaaFWUserConfig_Device';
export type { MaaFWUserConfig_Info } from './models/MaaFWUserConfig_Info';
export type { MaaFWUserConfig_Notify } from './models/MaaFWUserConfig_Notify';
export type { MaaFWUserConfig_Task } from './models/MaaFWUserConfig_Task';
export type { MaaPlanConfig } from './models/MaaPlanConfig';
export type { MaaPlanConfig_Info } from './models/MaaPlanConfig_Info';
export type { MaaPlanConfig_Item } from './models/MaaPlanConfig_Item';
export type { MaaUserConfig } from './models/MaaUserConfig';
export type { MaaUserConfig_Data } from './models/MaaUserConfig_Data';
export type { MaaUserConfig_Info } from './models/MaaUserConfig_Info';
export type { MaaUserConfig_Notify } from './models/MaaUserConfig_Notify';
export type { MaaUserConfig_Task } from './models/MaaUserConfig_Task';
export type { NoticeOut } from './models/NoticeOut';
export type { OCRScreenshotIn } from './models/OCRScreenshotIn';
export type { OCRScreenshotOut } from './models/OCRScreenshotOut';
export type { OkNteConfig } from './models/OkNteConfig';
export type { OkNteConfig_Game } from './models/OkNteConfig_Game';
export type { OkNteConfig_Info } from './models/OkNteConfig_Info';
export type { OkNteConfig_Run } from './models/OkNteConfig_Run';
export type { OkNteConfig_Script } from './models/OkNteConfig_Script';
export type { OkNteUserConfig } from './models/OkNteUserConfig';
export type { OkNteUserConfig_Data } from './models/OkNteUserConfig_Data';
export type { OkNteUserConfig_Info } from './models/OkNteUserConfig_Info';
export type { OkNteUserConfig_Notify } from './models/OkNteUserConfig_Notify';
export type { OkNteUserConfig_Task } from './models/OkNteUserConfig_Task';
export type { OkwwConfig } from './models/OkwwConfig';
export type { OkwwConfig_Game } from './models/OkwwConfig_Game';
export type { OkwwUserConfig } from './models/OkwwUserConfig';
export type { OkwwUserConfig_Data } from './models/OkwwUserConfig_Data';
export type { OkwwUserConfig_Info } from './models/OkwwUserConfig_Info';
export type { OkwwUserConfig_Notify } from './models/OkwwUserConfig_Notify';
export type { OkwwUserConfig_Task } from './models/OkwwUserConfig_Task';
export type { OpenClawQQQrCheckIn } from './models/OpenClawQQQrCheckIn';
export type { OpenClawQQQrCheckOut } from './models/OpenClawQQQrCheckOut';
export type { OpenClawQQQrStartOut } from './models/OpenClawQQQrStartOut';
export type { OpenClawQQStatusOut } from './models/OpenClawQQStatusOut';
export type { OpenClawWeixinQrCheckIn } from './models/OpenClawWeixinQrCheckIn';
export type { OpenClawWeixinQrCheckOut } from './models/OpenClawWeixinQrCheckOut';
export type { OpenClawWeixinQrStartOut } from './models/OpenClawWeixinQrStartOut';
export type { OpenClawWeixinStatusOut } from './models/OpenClawWeixinStatusOut';
export type { OutBase } from './models/OutBase';
export type { PatternDebugIn } from './models/PatternDebugIn';
export type { PatternDebugOut } from './models/PatternDebugOut';
export type { PatternDebugResultItem } from './models/PatternDebugResultItem';
export { PlanComboxIn } from './models/PlanComboxIn';
export { PlanCreateIn } from './models/PlanCreateIn';
export type { PlanCreateOut } from './models/PlanCreateOut';
export type { PlanDeleteIn } from './models/PlanDeleteIn';
export type { PlanGetIn } from './models/PlanGetIn';
export type { PlanGetOut } from './models/PlanGetOut';
export { PlanIndexItem } from './models/PlanIndexItem';
export type { PlanReorderIn } from './models/PlanReorderIn';
export type { PlanUpdateIn } from './models/PlanUpdateIn';
export type { PowerCountdownSnapshot } from './models/PowerCountdownSnapshot';
export { PowerIn } from './models/PowerIn';
export { PowerOut } from './models/PowerOut';
export type { PullCountStatistics } from './models/PullCountStatistics';
export { PushLogPattern } from './models/PushLogPattern';
export type { QrCheckIn } from './models/QrCheckIn';
export type { QrCheckOut } from './models/QrCheckOut';
export type { QrCreateOut } from './models/QrCreateOut';
export type { QrSaveIn } from './models/QrSaveIn';
export type { QueueConfig } from './models/QueueConfig';
export type { QueueConfig_Info } from './models/QueueConfig_Info';
export type { QueueCreateOut } from './models/QueueCreateOut';
export type { QueueDeleteIn } from './models/QueueDeleteIn';
export type { QueueGetIn } from './models/QueueGetIn';
export type { QueueGetOut } from './models/QueueGetOut';
export type { QueueIndexItem } from './models/QueueIndexItem';
export type { QueueItem } from './models/QueueItem';
export type { QueueItem_Data } from './models/QueueItem_Data';
export type { QueueItem_Info } from './models/QueueItem_Info';
export type { QueueItem_Schedule } from './models/QueueItem_Schedule';
export type { QueueItemCreateOut } from './models/QueueItemCreateOut';
export type { QueueItemDeleteIn } from './models/QueueItemDeleteIn';
export type { QueueItemGetIn } from './models/QueueItemGetIn';
export type { QueueItemGetOut } from './models/QueueItemGetOut';
export type { QueueItemIndexItem } from './models/QueueItemIndexItem';
export type { QueueItemReorderIn } from './models/QueueItemReorderIn';
export type { QueueItemUpdateIn } from './models/QueueItemUpdateIn';
export type { QueueReorderIn } from './models/QueueReorderIn';
export type { QueueSetInBase } from './models/QueueSetInBase';
export type { QueueUpdateIn } from './models/QueueUpdateIn';
export type { ScriptConfigImportIn } from './models/ScriptConfigImportIn';
export { ScriptCreateIn } from './models/ScriptCreateIn';
export type { ScriptCreateOut } from './models/ScriptCreateOut';
export type { ScriptDeleteIn } from './models/ScriptDeleteIn';
export type { ScriptFileIn } from './models/ScriptFileIn';
export type { ScriptGetIn } from './models/ScriptGetIn';
export type { ScriptGetOut } from './models/ScriptGetOut';
export { ScriptIndexItem } from './models/ScriptIndexItem';
export type { ScriptReorderIn } from './models/ScriptReorderIn';
export type { ScriptUpdateIn } from './models/ScriptUpdateIn';
export type { ScriptUploadIn } from './models/ScriptUploadIn';
export type { ScriptUrlIn } from './models/ScriptUrlIn';
export type { SettingGetOut } from './models/SettingGetOut';
export type { SettingUpdateIn } from './models/SettingUpdateIn';
export type { SklandLoginIn } from './models/SklandLoginIn';
export type { SrcConfig } from './models/SrcConfig';
export type { SrcConfig_Emulator } from './models/SrcConfig_Emulator';
export type { SrcConfig_Info } from './models/SrcConfig_Info';
export type { SrcConfig_Run } from './models/SrcConfig_Run';
export type { SrcUserConfig } from './models/SrcUserConfig';
export type { SrcUserConfig_Data } from './models/SrcUserConfig_Data';
export type { SrcUserConfig_Info } from './models/SrcUserConfig_Info';
export type { SrcUserConfig_Notify } from './models/SrcUserConfig_Notify';
export type { SrcUserConfig_Stage } from './models/SrcUserConfig_Stage';
export { TaskCreateIn } from './models/TaskCreateIn';
export type { TaskCreateOut } from './models/TaskCreateOut';
export type { TaskRuntimeSnapshot } from './models/TaskRuntimeSnapshot';
export { TaskRuntimeSnapshotItem } from './models/TaskRuntimeSnapshotItem';
export type { TaygedoLoginIn } from './models/TaygedoLoginIn';
export type { TimeSet } from './models/TimeSet';
export type { TimeSet_Info } from './models/TimeSet_Info';
export type { TimeSetCreateOut } from './models/TimeSetCreateOut';
export type { TimeSetDeleteIn } from './models/TimeSetDeleteIn';
export type { TimeSetGetIn } from './models/TimeSetGetIn';
export type { TimeSetGetOut } from './models/TimeSetGetOut';
export type { TimeSetIndexItem } from './models/TimeSetIndexItem';
export type { TimeSetReorderIn } from './models/TimeSetReorderIn';
export type { TimeSetUpdateIn } from './models/TimeSetUpdateIn';
export type { ToolsConfig } from './models/ToolsConfig';
export type { ToolsConfig_ArknightsPC } from './models/ToolsConfig_ArknightsPC';
export type { ToolsConfig_GameSign } from './models/ToolsConfig_GameSign';
export type { ToolsGetOut } from './models/ToolsGetOut';
export type { ToolsUpdateIn } from './models/ToolsUpdateIn';
export type { UpdateCheckIn } from './models/UpdateCheckIn';
export type { UpdateCheckOut } from './models/UpdateCheckOut';
export { UpdateDownloadSnapshot } from './models/UpdateDownloadSnapshot';
export type { UserCreateOut } from './models/UserCreateOut';
export type { UserDeleteIn } from './models/UserDeleteIn';
export type { UserGetIn } from './models/UserGetIn';
export type { UserGetOut } from './models/UserGetOut';
export type { UserInBase } from './models/UserInBase';
export { UserIndexItem } from './models/UserIndexItem';
export type { UserReorderIn } from './models/UserReorderIn';
export type { UserSetIn } from './models/UserSetIn';
export type { UserUpdateIn } from './models/UserUpdateIn';
export type { ValidationError } from './models/ValidationError';
export type { VersionOut } from './models/VersionOut';
export type { Webhook } from './models/Webhook';
export type { Webhook_Data } from './models/Webhook_Data';
export type { Webhook_Info } from './models/Webhook_Info';
export type { WebhookCreateOut } from './models/WebhookCreateOut';
export type { WebhookDeleteIn } from './models/WebhookDeleteIn';
export type { WebhookGetIn } from './models/WebhookGetIn';
export type { WebhookGetOut } from './models/WebhookGetOut';
export type { WebhookInBase } from './models/WebhookInBase';
export type { WebhookIndexItem } from './models/WebhookIndexItem';
export type { WebhookReorderIn } from './models/WebhookReorderIn';
export type { WebhookTestIn } from './models/WebhookTestIn';
export type { WebhookUpdateIn } from './models/WebhookUpdateIn';
export type { WebSocketMetaOut } from './models/WebSocketMetaOut';
export type { WSTaskCyclePreviewData } from './models/WSTaskCyclePreviewData';
export type { WSTaskScriptIdentityData } from './models/WSTaskScriptIdentityData';
export type { WSTaskScriptInfoData } from './models/WSTaskScriptInfoData';
export type { WSTaskUserInfoData } from './models/WSTaskUserInfoData';

export { Service } from './services/Service';
export { ActionService } from './services/ActionService';
export { AddService } from './services/AddService';
export { BetterGiService } from './services/BetterGiService';
export { ClawService } from './services/ClawService';
export { DeleteService } from './services/DeleteService';
export { GameSignService } from './services/GameSignService';
export { GetService } from './services/GetService';
export { HsrService } from './services/HsrService';
export { M9AService } from './services/M9AService';
export { MaaFwService } from './services/MaaFwService';
export { OcrService } from './services/OcrService';
export { OknteService } from './services/OknteService';
export { QqService } from './services/QqService';
export { UpdateService } from './services/UpdateService';
