#   AUTO-MAS: A Multi-Script, Multi-Config Management and Automation Software
#   Copyright © 2025-2026 AUTO-MAS Team
#
#   This file is part of AUTO-MAS.
#
#   AUTO-MAS is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License
#   as published by the Free Software Foundation, either version 3 of
#   the License, or (at your option) any later version.
#
#   AUTO-MAS is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with AUTO-MAS. If not, see <https://www.gnu.org/licenses/>.

from .app_options import (
    get_task_app_fields,
    get_task_app_jump,
    merge_plan_list,
    read_app_config,
    resolve_field_options,
    write_app_config,
)
from .backup_archive import (
    MAS_USER_INFO_FILE,
    archive_mas_backup,
    archive_onedragon_backup,
    collect_mas_user_info,
    get_mas_backup_dir,
    get_onedragon_backup_dir,
    list_mas_backups,
    list_onedragon_backups,
    native_registry_file,
    restore_mas_backup,
    restore_onedragon_backup,
)
from .catalog import list_app_catalog
from .compendium import (
    agent_id_options,
    agent_names,
    auto_battle_options,
    coffee_options,
    hollow_zero_challenge_options,
    hollow_zero_missions,
    lost_void_challenge_options,
    lost_void_missions,
    train_categories,
    world_patrol_route_lists,
)
from .native_config import (
    NATIVE_INSTANCE_RUN_OPTIONS,
    read_native_account_fields,
    read_native_instance_run,
    read_native_tasks,
    save_native_account_fields,
    save_native_instance_run,
    save_native_tasks,
)
from .notify import push_notification
from .zzz_od_config import (
    INSTANCE_RUN_ALL,
    INSTANCE_RUN_CURRENT,
    RUN_STATUS_FAILED,
    RUN_STATUS_NOT_RUN,
    RUN_STATUS_RUNNING,
    RUN_STATUS_SUCCESS,
    ZZZOD_GAME_LANGUAGE_LABELS,
    ZZZOD_GAME_REGION_LABELS,
    add_instance,
    backup_instance,
    clear_run_records,
    diff_run_records,
    expand_team_list,
    find_active_instance,
    find_free_instance_idx,
    instance_dir,
    list_instances,
    normalize_app_group_entries,
    predefined_team_options,
    read_app_group,
    read_game_account,
    read_team_list,
    remove_instance,
    rename_instance,
    restore_instance,
    restore_instance_view,
    set_active_instance,
    set_instance_active_in_od,
    set_instance_force_login,
    snapshot_run_records,
    validate_install,
    validate_root,
    write_app_group,
    write_game_account,
    write_instance_view,
    write_team_list,
)

__all__ = [
    "INSTANCE_RUN_ALL",
    "INSTANCE_RUN_CURRENT",
    "RUN_STATUS_FAILED",
    "RUN_STATUS_NOT_RUN",
    "RUN_STATUS_RUNNING",
    "RUN_STATUS_SUCCESS",
    "ZZZOD_GAME_LANGUAGE_LABELS",
    "ZZZOD_GAME_REGION_LABELS",
    "add_instance",
    "agent_id_options",
    "agent_names",
    "archive_mas_backup",
    "archive_onedragon_backup",
    "auto_battle_options",
    "backup_instance",
    "clear_run_records",
    "coffee_options",
    "collect_mas_user_info",
    "diff_run_records",
    "expand_team_list",
    "find_active_instance",
    "find_free_instance_idx",
    "get_mas_backup_dir",
    "get_onedragon_backup_dir",
    "get_task_app_fields",
    "get_task_app_jump",
    "hollow_zero_challenge_options",
    "hollow_zero_missions",
    "instance_dir",
    "list_app_catalog",
    "list_instances",
    "list_mas_backups",
    "list_onedragon_backups",
    "lost_void_challenge_options",
    "lost_void_missions",
    "MAS_USER_INFO_FILE",
    "merge_plan_list",
    "native_registry_file",
    "NATIVE_INSTANCE_RUN_OPTIONS",
    "normalize_app_group_entries",
    "predefined_team_options",
    "push_notification",
    "read_app_config",
    "read_app_group",
    "read_game_account",
    "read_native_account_fields",
    "read_native_instance_run",
    "read_native_tasks",
    "read_team_list",
    "remove_instance",
    "rename_instance",
    "resolve_field_options",
    "restore_instance",
    "restore_instance_view",
    "restore_mas_backup",
    "restore_onedragon_backup",
    "save_native_account_fields",
    "save_native_instance_run",
    "save_native_tasks",
    "set_active_instance",
    "set_instance_active_in_od",
    "set_instance_force_login",
    "snapshot_run_records",
    "train_categories",
    "validate_install",
    "validate_root",
    "world_patrol_route_lists",
    "write_app_config",
    "write_app_group",
    "write_game_account",
    "write_instance_view",
    "write_team_list",
]
